### ISSUE TITLE
Removing extra space in the app

### ISSUE THREAD

**Issue by ashuparija** [harjot-oberai/MusicStreamer#13]
When first downloaded, the app shows a white space(view) below in the screen which should be removed.
![screenshot_2016-08-19-18-15-37](https://cloud.githubusercontent.com/assets/16895031/17810534/5f6401fc-663b-11e6-85c4-2cc7079b62b1.png)
![screenshot_2016-08-19-18-15-21](https://cloud.githubusercontent.com/assets/16895031/17810539/65442cb4-663b-11e6-9f2c-27c609cc1874.png)

**Comment by deep110** [comment]
I think the solution could be if no song is available, make the view visibility gone.
