### ISSUE TITLE
Tutorial out of screen

### ISSUE THREAD

**Issue by icss91** [harjot-oberai/MusicStreamer#14]
The buttons "next" and "done" are out of screen on 2 tested devices, it's nearly impossible to tap on them to get further.

**Comment by harjot-oberai** [comment]
The problem may be with the library I am using, ShowcaseView. I have tested the app on multiple devices, of various screen size and android versions, but can't seem to find such an issue. Still I have added the code to automatically hide the ShowcaseView (Tutorial) once the back key is pressed. Its not an elegant solution, but having nothing to recreate the problem you are facing, this is the best that can be done.
