### ISSUE TITLE
error in build.gradle(Module.app)

### ISSUE THREAD

**Issue by Sumema** [harjot-oberai/MusicStreamer#15]
Error:(66, 14) Failed to resolve: com.crashlytics.sdk.android:crashlytics:2.6.2
cannot resolve this error please help!!!

//Code//

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }

```
    maven { url 'http://download.crashlytics.com/maven' }
}

dependencies {
    classpath 'io.fabric.tools:gradle:1.+'
    classpath 'com.crashlytics.tools.gradle:crashlytics-gradle:1.+'
}
```

}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

apply plugin: 'com.android.application'
apply plugin: 'crashlytics'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

```
defaultConfig {
    applicationId "com.sdsmdg.harjot.MusicDNA"
    minSdkVersion 19
    targetSdkVersion 23
    versionCode 24
    versionName "0.9.95"
    renderscriptTargetApi 19
    renderscriptSupportModeEnabled true
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'

```
compile 'com.android.support:appcompat-v7:23.4.0'
compile 'jp.wasabeef:recyclerview-animators:2.2.3'
compile 'com.squareup.retrofit:converter-gson:2.0.0-beta1'
compile 'com.squareup.retrofit:retrofit:2.0.0-beta1'
compile 'com.squareup.okhttp:okhttp:2.2.+'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.+'
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'de.hdodenhof:circleimageview:2.0.0'
compile 'com.android.support:support-v4:23.4.0'
compile 'com.android.support:design:23.4.0'
compile 'bz.tsung.android:objectify:1.1.1'
compile 'com.android.support:cardview-v7:23.4.0'
compile 'com.android.support:palette-v7:23.4.0'
compile 'com.wang.avi:library:1.0.5'
compile 'com.nineoldandroids:library:2.4.0'
compile 'com.diogobernardino:williamchart:2.2'
compile 'tyrantgit:explosionfield:1.0.1'
compile 'com.google.code.gson:gson:2.5'
compile 'com.h6ah4i.android.widget.verticalseekbar:verticalseekbar:0.7.0'
compile 'jp.wasabeef:blurry:2.0.2'
compile 'me.priyesh:chroma:1.0.2'
compile 'com.github.amlcurran.showcaseview:library:5.4.3'
compile('com.crashlytics.sdk.android:crashlytics:2.6.2@aar') {
    transitive = true;
}
```

}

**Comment by hareshkh** [comment]
I think there is no problem with the dependencies in the `build.gradle` file. Clean and Rebuild the project. Make sure you are on an active internet connection due to online dependencies. I recently did a successful build on my laptop.

**Comment by Sumema** [comment]
Thank you for the assistance.
Could you please tel if this project is connected to database.If yes, then
which one!!

Thanks
Regards,

**Comment by harjot-oberai** [comment]
No, the project is not connected to any database. Everything is stored locally, using methods provided by the by sdk.

**Comment by Sumema** [comment]
okay thanks

**Comment by Sumema** [comment]
Can you please tell why does it show "Unfortunately Stopped app_name" error.
