### ISSUE TITLE
SoundCloud search doesn't work

### ISSUE THREAD

**Issue by icss91** [harjot-oberai/MusicStreamer#16]
Seems like soundcloud API is not working, or is there a bug with the new release?

**Comment by harjot-oberai** [comment]
The issue is with the SoundCloud API. The search was fine even after the last release and was working till last week. I am looking into the issue.

**Comment by harjot-oberai** [comment]
SoundCloud has probably blocked all API calls from my Client ID and has not replied to me regarding the issue. The app on the app store will be updated with a new API key, but for development purposes, anyone willing to clone and build on their local machines will have to get a new API key from SoundCloud. Exact Instructions have been added in the readme.
