### ISSUE TITLE
Unintentionally committed secret in file fabric.properties?

### ISSUE THREAD

**Issue by yarwelp** [harjot-oberai/MusicStreamer#17]
https://github.com/harjot-oberai/MusicStreamer/blob/master/app/fabric.properties

**Comment by zengjiaozi** [comment]
why i can not find the config.java ?

**Comment by harjot-oberai** [comment]
@zengjiaozi : See build instructions.
@eriknstr  : thanks for pointing out. the file will be removed from next commit.
