### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by airon90** [harjot-oberai/MusicStreamer#24]
Please, add your app on F-Droid. See [how to submit an app](https://f-droid.org/contribute/) on F-Droid catalogue.

**Comment by IzzySoft** [comment]
And if you find that too troublesome: maybe you at least consider adding the `.apk` here at Github (best in `releases/`, see [Creating Releases](https://help.github.com/articles/creating-releases/))? I could then pick it up and add it to [my F-Droid compatible repo](https://android.izzysoft.de/repo), keeping your signature. Updates would then be available within 24h of your adding them here :)

**Comment by Poussinou** [comment]
This app on F-Droid will be amazing !

**Comment by IzzySoft** [comment]
@Poussinou [It is, in a way](https://android.izzysoft.de/repo/apk/com.sdsmdg.harjot.MusicDNA) now. You'd just need to add my repo to your F-Droid client :smiley_cat:

The "official repo" might choke on e.g. Crashlytics, which is integrated with the player, and thus not accept it.

@harjot-oberai For an alternative to require the `READ_PHONE_STATE` (which in connection with `INTERNET` always looks suspicious, as thanks to some ad networks the first thought is you might wish to transmit device IDs), take a look at [my post here](https://android.stackexchange.com/questions/605/why-do-so-many-applications-require-permission-to-read-the-phone-state-and-ident/62968#62968). There are ways to detect an incoming call by other means that via that permission. In short, as an incoming call "rings the bell", just register for the `onAudioFocusChange()`; then check whether it was triggered by a call (checking current CallState does not require any permission). Just as a hint :stuck_out_tongue_winking_eye:

**Comment by harjot-oberai** [comment]
@IzzySoft : Thank you very much.
I added the release apk today here on github after reading @Poussinou comment. Then I remembered that you had offered to upload the apk on your F-Droid repo. Sorry for keeping you waiting for so long.

Also the `READ_PHONE_STATE` permission; I have received at least 10 bad reviews just for that. Thanks for suggesting the workaround, I'll surely implement it as soon as possible.

I will add the F-Droid banner as well and link your repo to it 👍

**Comment by IzzySoft** [comment]
@harjot-oberai Yeah, that's what I meant by "looking suspicious". Some US president once said, "90% of our politicians make the remaining 10% look bad", same here: There've been too many abuses in the past, and permissions are very far from being fine-grained. Unfortunately, the way via `READ_PHONE_STATE` is the one recommended via the developer docs, and at that the only one mentioned (and really easy to implement, as far as I've heard – I'm not an Android dev myself, just an "Android Enthusiast" trying to make the world a better place :smile_cat: ). The work-around I recommended is a bit harder, keeping my fingers crossed for an easy go! Maybe one day someone makes that a little module others can simply add to their apps (wink, wink ;)

> I added the release apk today here on github

Thanks a lot, in the name of all your users who wanted that – present and future :)

> I will add the F-Droid banner as well and link your repo to it :+1:

Very much appreciated, thanks! Makes it easier for interested users to find it!

**Comment by Poussinou** [comment]
Thanks a lot guys, you're amazing :) this app is beautiful

**Comment by IzzySoft** [comment]
@harjot-oberai if you've implemented the alternative approach to "phone state", please let me know (including how difficult it was, and maybe hints you would give to other developers to save them some headaches). Might convince some of them, and make several apps "look cleaner" :wink: 

PS: I just learned about the effect an F-Droid icon with a download link behind it can have. 284 downloads of the `.apk` already on my end – which makes 15+ downloads a day on average :scream_cat::stuck_out_tongue_winking_eye: As only 77 "referrers" account for your GH repo, it seems it's picked up directly via the F-Droid client pretty well, too :innocent:
