### ISSUE TITLE
Several fixes regarding gitignore.

### ISSUE THREAD

**Issue by deep110** [harjot-oberai/MusicStreamer#32]
- Remove absolute path of Config.java.  Also add a sample Config file so that anyone can build the project using their own key values.
- Add .idea files to it

**Comment by hareshkh** [comment]
@deep110 : For adding a default `Config.java` and then make **git** not track it every user has to run
`git update-index --assume-unchanged <filename>` after clone. So if something is expected after clone and before first build it is better to add a `Config.java` rather than running this command.
