### ISSUE TITLE
Could not download gradle.jar (io.fabric.tools:gradle:1.22.0)

### ISSUE THREAD

**Issue by zhenxun815** [harjot-oberai/MusicStreamer#47]
I can download gradle-1.22.0.jar from the browser,but build failed in Android Studio:

A problem occurred configuring root project 'MusicDNA-master'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not download gradle.jar (io.fabric.tools:gradle:1.22.0)
      > Could not get resource 'https://maven.fabric.io/public/io/fabric/tools/gradle/1.22.0/gradle-1.22.0.jar'.
         > Could not GET 'https://maven.fabric.io/public/io/fabric/tools/gradle/1.22.0/gradle-1.22.0.jar'.
            > Connect to fabric-artifacts.s3.amazonaws.com:443 [fabric-artifacts.s3.amazonaws.com/54.231.114.146] failed: Connection timed out: connect

finally,I have to remove the Fabric...

**Comment by harjot-oberai** [comment]
There might have been issue with your internet connection or maven.fabric.io might have been down, is it working now or not ?

**Comment by zhenxun815** [comment]
I don't konw,I removed the code associated with Fabric thereby  building the project successfully.
Anyway,  it's not an obstacle to reading the code without Fabric.
