### ISSUE TITLE
crash when searching lyric

### ISSUE THREAD

**Issue by indra365** [harjot-oberai/MusicStreamer#49]
App crash every time I tap searching lyric, (genius API key has been added)
Also it always ask for permission every time it opened

**Comment by harjot-oberai** [comment]
The crash was related to exception handling in lyrics base classes (IllegalStateException was never being handled). This issue has been fixed 👍 
Regarding permissions, which permission are you talking about exactly? If you have to give all the permissions every time you open the app, then the issue will most probably with how your phone handles permissions for applications. Their might be such an option in the settings or developer options of your phone. Which phone are you currently using ?
