### ISSUE TITLE
License, 

### ISSUE THREAD

**Issue by Mardoqueu** [harjot-oberai/MusicStreamer#51]
Is this project for free use? Since, of course, referencing the author?

**Comment by suyashmahar** [comment]
MusicDNA is licensed under __Creative Commons Non-Commercial Share Alike license__ (CC-NC-by-SA) complete license is [here](https://github.com/harjot-oberai/MusicDNA/blob/master/LICENSE.md)

**Comment by harjot-oberai** [comment]
@Mardoqueu : The project is free to use and distribute as long as it is not used for any commercial purpose like selling advertisements etc.

**Comment by Jaymin-Bhadani** [comment]
Hello But Some One Already use as commercial (with advertisements) ???

**Comment by harjot-oberai** [comment]
Can you give me a link to the app you are talking about, so we can report it.

**Comment by Jaymin-Bhadani** [comment]
Can I sent you in private ?

**Comment by harjot-oberai** [comment]
email me at harjot.oberai@gmail.com

**Comment by Jaymin-Bhadani** [comment]
and i find one project from github https://github.com/collinx/MusicStreamer#license it same as you and it have "MusicStreamer (MusicDNA) is under MIT 2016 Licens" ??

**Comment by ramafunapps** [comment]
Hi, Are we allowed to use it for commercial purpose like adding Ads?
This is the same project under MIT https://github.com/collinx/MusicStreamer#license 
Please let me know if license changed.

**Comment by suyashmahar** [comment]
@ramafunapps, @Jaymin-Bhadani Thank you for noticing, license is changed and latest version of which is available [here](https://github.com/harjot-oberai/MusicDNA/blob/master/LICENSE.md). Current license does not allow any commercial use.

**Comment by ramafunapps** [comment]
so this license is invalid?? Can you remove it if so.. because you are confusing other developers.
MIT https://github.com/collinx/MusicStreamer#license

**Comment by harjot-oberai** [comment]
@ramafunapps, @collinx has updated the license in his fork of the project.
