### ISSUE TITLE
Firebase Support?

### ISSUE THREAD

**Issue by power7714** [harjot-oberai/MusicStreamer#54]
Can Firebase be used as the source for audio files with this project?

**Comment by harjot-oberai** [comment]
No. Why would you want to stream audio from firebase ?

**Comment by power7714** [comment]
Its for an in house audio messaging app. Sort of like a cb radio.

**Comment by harjot-oberai** [comment]
Well you may try it implement it yourself (see how streaming works from SoundCloud), but the app does not support streaming from firebase, 
I'll won't be adding this feature myself.
