### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [harjot-oberai/MusicStreamer#58]
Hi @harjot-oberai 

I found [this app](https://play.google.com/store/apps/details?id=com.defaultmusicplayerforandroid)  on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software (but they claim to be based on your source code...)

I don't know if you agree with this kind of "work", but because you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the fake app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is free software and this guy is violating the license;
* He is falsely claiming he made the app;
* Include screenshots of your app.

**Comment by harjot-oberai** [comment]
Thank you @Poussinou for notifying me. The app does violate the license and has been reported.
Cheers 🍺

**Comment by Poussinou** [comment]
@harjot-oberai 
I also found those below:
* https://play.google.com/store/apps/details?id=com.soundcloud.audio.video.musicplayer
* https://play.google.com/store/apps/details?id=com.megaweb.vibesoundmusic
* https://play.google.com/store/apps/details?id=com.mp3musicplayer.musicstreaming.freemusic
* https://play.google.com/store/apps/details?id=com.msb.msbstudio.MSBMusicPlayer
* https://play.google.com/store/apps/details?id=com.musictrending.freemusic

You should maybe take some time to search for copies of Music DNA on the Play Store, for example just by typing Music DNA in the research bar, and have a look at each app proposed by the Play Store. It takes 15 minutes with a good connexion but it is a simple way to find copies of your app. If you find more than the ones I already mentioned, please copy-paste the links here, so that I can track the fake developers :)

**Comment by harjot-oberai** [comment]
@Poussinou Thanks again for finding copies of the app. I will surely look for more copies and update the list accordingly.

**Comment by Poussinou** [comment]
Another one here: https://play.google.com/store/apps/details?id=com.hit.freemusic

**Comment by Poussinou** [comment]
* https://play.google.com/store/apps/details?id=com.sdsmdg.bitnet.retrohighmusics from [this developer](https://play.google.com/store/apps/developer?id=Trillium+Apps)
