### ISSUE TITLE
Config file is missing 

### ISSUE THREAD

**Issue by mehulTank** [harjot-oberai/MusicStreamer#64]
i have clone repository but whenever i run app getting error config file is missing can you please update ?

**Comment by TacoTheDank** [comment]
how about read the damn README.md that says EXACTLY WHAT TO DO

**Comment by harjot-oberai** [comment]
@TacoTheDank : Everyone is just trying to figure out stuff, no need to be rude.

@mehulTank : See here : [https://github.com/harjot-oberai/MusicDNA#build-instructions](https://github.com/harjot-oberai/MusicDNA#build-instructions)

**Comment by TacoTheDank** [comment]
@harjot-oberai lol sorry was frustrated yesterday (but it does also irritate me when people don't even take the time to read)
