### ISSUE TITLE
Add video demo

### ISSUE THREAD

**Issue by CodeMaxx** [harjot-oberai/MusicStreamer#7]
Add a video of about 10 seconds in the `Player in Action` section. The screenshots don't make it very clear how the feel would be while actually using it.

**Comment by harjot-oberai** [comment]
10 second video would not have been enough, so i have added a 3:00 min video of the player.

**Comment by CodeMaxx** [comment]
I said 10 seconds just to keep the size of the repo small. 3 minutes is better if that is not a concern. 😄
