### ISSUE TITLE
Hard time exiting the player in the notification

### ISSUE THREAD

**Issue by icss91** [harjot-oberai/MusicStreamer#9]
Also, when closing the app it often crashes

**Comment by Dirkstaal** [comment]
He is currently working on it :) which android version do you use ?

**Comment by icss91** [comment]
I am on 6.0.1

**Comment by Dirkstaal** [comment]
Yes he is working on the notification controls and errors ect

**Comment by harjot-oberai** [comment]
yup, I know about the issue in marshmallow, I am currently testing on a lollipop device.
For marshmallow, i just made sure that the basic things are working.
I got to know about the issue about 20 days back, when  i tested on my brother's phone.
I am looking into it and resolve it as soon as possible.

**Comment by icss91** [comment]
Cool, keep up the great work!
